const DatosQuery = [
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "19",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "20",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "17",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "PUBLICADA",
    Empresa: "FISA",
    Dia: "20",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "24",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "4",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "18",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "25",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "3",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "3",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "18",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "25",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "13",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "5",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "4",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "3",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "4",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "17",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "13",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "3",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "5",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "PUBLICADA",
    Empresa: "FISA",
    Dia: "20",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "19",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "19",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "24",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "4",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "4",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "4",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "13",
  },
  {
    Tipo_credito: "ALTOPERFIL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "1",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "17",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "4",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "18",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "5",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "13",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "25",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "SUSPENDIDA",
    Empresa: "FISA",
    Dia: "24",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "13",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "25",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "ALTOPERFIL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "18",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "1",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "14",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "19",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "18",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "21",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "PUBLICADA",
    Empresa: "AEF",
    Dia: "19",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "19",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "20",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "27",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "5",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "3",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "4",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "5",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "24",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "3",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "5",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "APROBADA",
    Empresa: "FISA",
    Dia: "3",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "12",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "12",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "3",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "25",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "22",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "17",
  },
  {
    Tipo_credito: "FORMALDIGITAL",
    status: "RECHAZADA",
    Empresa: "AEF",
    Dia: "24",
  },
  {
    Tipo_credito: "PENSIONADOS",
    status: "RECHAZADA",
    Empresa: "FISA",
    Dia: "20",
  },
];

export default DatosQuery;


